Prep javascript operators and expressions
PhilChoe/javascript-prep-0624-code-solutions pull request #6
Opened 2024-06-19 05:40 UTC by PhilChoe

![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/a13f90c2-a00d-4057-9a4f-8f0cedc25734)

2024-06-19 05:41 UTC, PhilChoe commented
I would love some feedback on the coding itself, is this correct, is there a way to simplify it or a more universally accepted way to format it? Thank you!

2024-06-19 16:16 UTC, shawnkost requested changes
Nicely done Philip! Functionally, this looks great! I requested some changes on variable keywords.

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +var number2 = 4;
If you remember in the Q&A for `prep-javascript-variables`, I mentioned that `var` is an outdated way of creating variables. It still works, but here at LearningFuze, we will only use `const` or `let`. In this specific example these should be `const`

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +prod = number1 * number2;
Since `prod` is a new variable that you're creating, it needs a variable initializer like `const`

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +var payment = 5;
Same note about making these `const`

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +amountRemaining = charge - payment;
Needs a variable initializer keyword

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +var finals = 3;
Same note about making these `const`

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +grade = (tests + assignments + finals) / 3;
Needs a variable initializer keyword

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +var pH = 2;
Same note about making this `const`

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +isAcidic = pH < 7;
Needs a variable initializer keyword

2024-06-19 16:16 UTC, shawnkost commented on prep-javascript-operators-and-expressions/main.js
> +var numberOfSoldiers = 100;
Same note about making this `const`

2024-06-20 04:40 UTC, PhilChoe commented
![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/e7c983a2-e322-4ef5-97e5-5b656aff7199)

2024-06-20 21:17 UTC, PhilChoe commented
![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/74543039-2c80-4262-9fa1-5f60cf4fad17)

2024-06-20 21:56 UTC, robgmerrill approved these changes
👍

2024-06-20 21:56 UTC, merged