Completed Javascript-objects
PhilChoe/javascript-prep-0624-code-solutions pull request #7
Opened 2024-06-19 06:15 UTC by PhilChoe

![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/171484e2-4cc4-49d0-a986-e8643578a8bb)

2024-06-19 16:32 UTC, shawnkost requested changes
Just missing one `console.log` here!

2024-06-19 16:32 UTC, shawnkost commented on prep-javascript-objects/main.js
> +console.log("The person's previous job was", person['previousJob']);
Missing one final console log for the whole `person` object.

2024-06-20 04:25 UTC, PhilChoe commented
![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/dfee62d7-53f2-4895-80ff-51fe4ec8b762)

2024-06-20 04:27 UTC, PhilChoe commented
![image](https://github.com/PhilChoe/javascript-prep-0624-code-solutions/assets/172565484/1264f63e-7627-4ead-8096-49bd75f0371d)

2024-06-20 16:01 UTC, robgmerrill approved these changes
👍

2024-06-20 16:43 UTC, merged